name = "katelyatv"

compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# 默认 D1 数据库配置（用于命令行操作）
[[d1_databases]]
binding = "DB"
database_name = "katelyatv-db"
database_id = "a3014e9d-6c6b-49fa-9007-03bb8239e397"

